services:
  - type: web
    name: everyday-experience-hunt
    runtime: static
    staticPublishPath: .
    buildCommand: ""
  - type: web
    name: memory-archive
    runtime: static
    staticPublishPath: ./memory-archive
    buildCommand: ""
  - type: web
    name: experience-hunt-2
    runtime: static
    staticPublishPath: ./hunt2
    buildCommand: ""
  - type: web
    name: experience-hunt-3-mobility
    runtime: static
    staticPublishPath: ./hunt3-mobility
    buildCommand: ""
  - type: web
    name: experience-hunt-4
    runtime: static
    staticPublishPath: ./hunt4
    buildCommand: ""
